### ISSUE TITLE
Destroying Domain on Azure Fails

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#18]
When trying to destroy a domain (resource group) on Azure the following error appears:
```
[vagrant@controller ~]$ cloudware domain destroy --name crafty-caribou
[OK]  Checking domain exists
error: {oying domain crafty-caribou
  "message": "Long running operation failed with status 409",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "https://management.azure.com/subscriptions/d1e964ef-15c7-4b27-8113-e725167cee83/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1DUkFGVFk6MkRDQVJJQk9VLVVLU09VVEgiLCJqb2JMb2NhdGlvbiI6InVrc291dGgifQ?api-version=2017-05-10",
    "method": "get",
    "path_params": null,
    "skip_encoding_path_params": null,
    "query_params": null,
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json;charset=utf-8",
      "Accept": "application/json",
      "accept-language": "en-US",
      "x-ms-client-request-id": "3a30a87f-1371-4129-a842-6c4af0f77a99"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"Error\":{\"Code\":\"ResourceGroupDeletionBlocked\",\"Target\":null,\"Message\":\"Deletion of resource group 'crafty-caribou' failed as resources with identifiers 'Microsoft.Network/virtualNetworks/network' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is '719b2d3d-1117-4f0e-a349-05331165380d'. Please check audit logs for more details.\",\"Details\":[{\"Code\":null,\"Target\":\"/subscriptions/d1e964ef-15c7-4b27-8113-e725167cee83/resourceGroups/crafty-caribou/providers/Microsoft.Network/virtualNetworks/network\",\"Message\":\"{\\\"error\\\":{\\\"code\\\":\\\"InUseSubnetCannotBeDeleted\\\",\\\"message\\\":\\\"Subnet prv is in use by /subscriptions/d1e964ef-15c7-4b27-8113-e725167cee83/resourceGroups/crafty-caribou-master1/providers/Microsoft.Network/networkInterfaces/crafty-cariboumaster1prv/ipConfigurations/crafty-cariboumaster1-prv and cannot be deleted.\\\",\\\"details\\\":[]}}\",\"Details\":null,\"Innererror\":null}],\"Innererror\":null}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "x-ms-ratelimit-remaining-subscription-reads": "14998",
      "x-ms-request-id": "2dddb76b-b8b6-4cfb-a742-7e4356f56b05",
      "x-ms-correlation-request-id": "2dddb76b-b8b6-4cfb-a742-7e4356f56b05",
      "x-ms-routing-request-id": "UKWEST:20180430T085004Z:2dddb76b-b8b6-4cfb-a742-7e4356f56b05",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "x-content-type-options": "nosniff",
      "date": "Mon, 30 Apr 2018 08:50:04 GMT",
      "connection": "close",
      "content-length": "959"
    },
    "status": 409
  }
}
	from /opt/cloudware/vendor/ruby/2.4.0/gems/ms_rest_azure-0.9.0/lib/ms_rest_azure/azure_service_client.rb:207:in `get_async_with_custom_deserialization'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/ms_rest_azure-0.9.0/lib/ms_rest_azure/azure_service_client.rb:157:in `update_state_from_location_header'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/ms_rest_azure-0.9.0/lib/ms_rest_azure/azure_service_client.rb:50:in `block in get_long_running_operation_result'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/timer_task.rb:309:in `execute_task'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/scheduled_task.rb:285:in `process_task'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/timer_set.rb:168:in `block (2 levels) in process_tasks'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

This seems to indicate that the resources are being deleted in an order not supported by Azure (network being deleted before resources that are on that network).

**Comment by ColonelPanicks** [comment]
This seems to be expected behaviour due to machines existing in the domain. Fix such that destroying a domain will delete the machines within it.

**Comment by ColonelPanicks** [comment]
Presumably a similar thing is occurring with AWS except a lot less verbose:
```
[vagrant@controller ~]$ cloudware domain destroy --name laces
[OK]  Checking domain exists
error: stopped waiting, encountered a failure state. Use --trace to view backtrace
```

Note: adding `--trace` seems to just make this command hang for longer

**Comment by ColonelPanicks** [comment]
Cannot replicate issues. Closing.
