### ISSUE TITLE
Can't Destroy Empty Domain

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#19]
Lists of current domains and machines:
```
[vagrant@controller ~]$ cloudware domain list
[OK]  Fetching available domains
+----------------+--------------+-----------------+-----------------+----------+-----------+
| Domain name    | Network CIDR | Prv Subnet CIDR | Mgt Subnet CIDR | Provider | Region    |
+----------------+--------------+-----------------+-----------------+----------+-----------+
| laces          | 10.0.0.0/16  | 10.0.1.0/24     | 10.0.2.0/24     | aws      | eu-west-1 |
| prickly-pigeon | 10.0.0.0/16  | 10.0.1.0/24     | 10.0.2.0/24     | aws      | eu-west-1 |
+----------------+--------------+-----------------+-----------------+----------+-----------+
[vagrant@controller ~]$ cloudware machine list
[OK]  Fetching available machines
+------+--------+------+----------------+----------------+------+-------+
| Name | Domain | Role | Prv IP address | Mgt IP address | Type | State |
+------+--------+------+----------------+----------------+------+-------+
+------+--------+------+----------------+----------------+------+-------+
```

Attempting to delete `prickly-pigeon`
```
[vagrant@controller ~]$ cloudware domain destroy --name prickly-pigeon --trace
[OK]  Checking domain exists
/opt/cloudware/lib/cloudware/domain.rb:93:in `destroy': Unable to destroy domain with active machines (RuntimeError)
	from /opt/cloudware/lib/cloudware/cli.rb:134:in `block (2 levels) in <class:CLI>'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /opt/cloudware/vendor/ruby/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /opt/cloudware/bin/cloudware:32:in `<main>'
```

Checked on AWS and there are no ec2 instances containing that name and no resources tagged with `cloudware_name: prickly-pigeon` besides the VPC (which it should then delete).

This issue may be specific to this domain but in case it isn't (despite having been able to delete _other_ aws domains) then this issue can be used to track any other domains that have issues to prevent this going forwards.

**Comment by ColonelPanicks** [comment]
It's okay because nothing else has had this issue, closing!
